### ISSUE TITLE
Vertical Flip does not apply for the whole image with DroidCamX

### ISSUE THREAD

**Issue by Trenar** [dev47apps/droidcam#147] opened 2021-02-23 16:57 UTC
**Describe the bug**
When using 'vertical flip' in the desktop app, a small line (approx. 5 pixel) on the bottom of the image remains on the bottom and freezes, i.e. does not get flipped correctly. See the areas between my fingers, where the bottom line does not change, when my fingers are pointing upwards.

![tmp2](https://user-images.githubusercontent.com/31891152/108878451-919d1300-7600-11eb-972c-38e14449097e.gif)

This does *not* happen with DroidCam App, only DroidCamX

**Expected behavior**
flip the complete image

**Additional context**
Ubuntu/Linux Server v1.7.1, DroidCamX Client 6.9.3

**Comment by aramg** [comment] 2021-03-03 23:33
Hi, does this happen with all resolutions?
640x480
1280x720
1920x1080

**Comment by Trenar** [comment] 2021-03-04 08:27
Hi aramg,
I tried following the guide to change the settings, but can't unload the v4l2loopback_dc module.. Any suggestions? 

cmd:
`lsmod | grep _dc`
output:
`v4l2loopback_dc        24576  1`
`videodev              237568  7 rmi_core,videobuf2_v4l2,v4l2loopback_dc,uvcvideo,videobuf2_common`

cmd:
`sudo rmmod v4l2loopback_dc`
output:
`rmmod: ERROR: v4l2loopback_dc is in use`

**Comment by aramg** [comment] 2021-03-04 17:26
1. You'll need to make sure the video device is not in use - so close other programs like OBS, Zoom, Skype, and even Chrome/Firefox if those are used for eg. Google meet.

2. In your GIF above, the quality of the image looks pretty low, so this can also be caused by that. Did you set the Video Quality to low in DroidCamX? (or is the low quality just a result of converting to GIF?)

**Comment by Trenar** [comment] 2021-03-11 14:45
Hi aramg,

it does *not* happen @ 1280x720 and 640x480, but at 1920x1080, 960x720 and 800x600.

I took two webcam images where in both, 800x600 and 1920x1080, the lower border is 8 pixels high. 

I hope this helps.
Cheers,
Trenar

**Comment by Trenar** [comment] 2021-03-16 08:14
Forgot to answer your second question.. I downsized the gif, since github has a 5 MB file size limit. The original video was 1080p.

**Comment by aramg** [comment] 2021-03-16 18:32
Got it. My initial guess is maybe the phone camera is not capturing at those resolutions, and the process of re-sizing and then flipping causes the artifacts. When the phone capture resolution matches the output, no re-size is needed and the artifacts don't appear.

**Comment by aramg** [comment] 2021-07-15 21:37
Closing this since (a) standard resolutions work, (b) no other queries have come in.
I think the plan would be to re-write the client and use OpenGL.

**Closed by aramg** 2021-07-15 21:37 UTC
