### ISSUE TITLE
Skype blackscreen with high resolution on Ubuntu 18.04

### ISSUE THREAD

**Issue by EugenIvanou** [dev47apps/droidcam#138] opened 2021-02-02 16:30 UTC
Hi, on my Ubuntu 18.04, kernel: 4.15.0.135, Skype version 8.68.0.100, 'Droidcam' listed on the list, but it's not working as expected I''ve tried it with 1080p and 720p resolution, but it shows  black screen, I'm confused little bit because with 640x480 it works. I'm using latest Droidcam client 1.7.1, but on 1.6 it was the same.

I've installed video driver Droidcam v4l2loopback-dc following instruction: [install video](https://www.dev47apps.com/droidcam/linux/) and no success at all.
OBS, Google Meet - works perfectly.

Would you recommend something to me? Thanks in advance.

**Comment by aramg** [comment] 2021-02-02 18:13
If it works in other apps, its likely a Skype issue. Not sure what I could suggest.
Make sure the resolutions you entered are correct (exactly 1280x720 or 1980x1080).
You can also try installing v4l2loopback-dkms and try DroidCam + Skype with it.

Closing this as a support question and not a bug.

**Closed by aramg** 2021-02-02 18:13 UTC
